#!/usr/bin/env bash
#configures an Ubuntu server 
localhost_ip="127.0.0.2"
facebook_ip="8.8.8.8"

cp /etc/hosts ~/hosts.new
echo "127.0.0.2	localhost" > ~/hosts.new
echo "8.8.8.8	facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
